# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(default='happy', max_length=20),
            preserve_default=False,
        ),
    ]
