# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='units',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
